# Generated by Django 5.2.5 on 2025-08-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('field_id', models.CharField(db_column='_id', max_length=24, primary_key=True, serialize=False)),
                ('disease', models.CharField(max_length=100)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('field_id', models.CharField(db_column='_id', max_length=24, primary_key=True, serialize=False)),
                ('disease', models.CharField(max_length=100)),
                ('information', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'treatments',
                'managed': False,
            },
        ),
    ]
