# Generated by Django 5.2.5 on 2025-10-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name_plural': 'Statistics'},
        ),
    ]
