# Generated by Django 5.2.5 on 2025-11-12 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blog_user_alter_statistics_options_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.JSONField()),
                ('disease_1', models.CharField(max_length=100)),
                ('disease_2', models.CharField(max_length=100)),
                ('disease_3', models.CharField(max_length=100)),
                ('prob_1', models.FloatField()),
                ('prob_2', models.FloatField()),
                ('prob_3', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.user')),
            ],
            options={
                'db_table': 'prediction_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
